<?php if (isset($action) && $action != ''): ?>
<h1 style="font-size: 32px; margin: 8px 0 23px 0; text-align: center; font-family: 'Raleway', serif;"><?php echo $action === "personal" ? "Personal Projects" : "Work History"; ?></h1>
<?php endif; ?>

<!-- sort method options -->
<p id="sorts"> 
	Sort by: &nbsp;
	<a href="<?php echo $action; ?>?page=<?php echo $current_page; ?>&sortby=alpha_asc">
		Alphabet (ascending)
	</a> &nbsp;|&nbsp;
	<a href="<?php echo $action; ?>?page=<?php echo $current_page; ?>&sortby=alpha_desc">
		Alphabet (descending)
	</a> &nbsp;|&nbsp;
	<a href="<?php echo $action; ?>?page=<?php echo $current_page; ?>&sortby=date_asc">
		Date (ascending)
	</a> &nbsp;|&nbsp;
	<a href="<?php echo $action; ?>?page=<?php echo $current_page; ?>&sortby=date_desc">
		Date (descending)
	</a>
</p>

<!-- pagination controls -->
<?php
/* grabbed directly from official Zend tutorial */
// add at the end of the file after the table
echo $this->paginationControl(
    // the paginator object
    $gallery_items,
    // the scrolling style
    'sliding',
    // the partial to use to render the control
    'partial/paginator.phtml',
    // the route to link to when a user clicks a control link
    array(
        'route' => 'index'
    )
);
?>

<!-- main project thumbnail display -->
<div class="row">
<div class="col-xs-10 col-xs-offset-1" id="portfolioDisplay">
	<?php 
	// example of fetching db items
	foreach($gallery_items as $item) {
	?>

	<a class="itemLink" href="/<?php echo $item->url_key; ?>">
	<?php
		// if portfolio item doesn't have an image (filename), just render
		// the blank image
		$empty_img = false;
		if ($item->img_filename === null) {
			$img_filename = 'placeholder.png';
			$empty_img = true;
		} else {
			$img_filename = $item->img_filename;
		}

		$img_filename = "/sym/images/" . $img_filename;
	?>
	<div class="itemThumbnail <?php if ($empty_img) { echo 'empty-img'; } ?>" style="background-image: url('<?php echo $img_filename; ?>');">
		
		<!-- 
			invisible until user hovers over the thumbnail.
			only background is filtered by opacity.
		-->
		<div class="thumbContent">
			<p class="thumbOverlay">
			</p>
			<p class="thumbText">
				<?php echo $item->title ?><br/>

				<span style="font-size: 14px; font-style: italic;"><?php echo $item->getPortfolioTypeName($item->portfolio_type); ?></span>
			</p>
		</div>

		<div class="touchScreenDesc">
			<?php echo $item->title ?><br/>

			<span style="font-size: 14px; font-style: italic;"><?php echo $item->getPortfolioTypeName($item->portfolio_type); ?></span>
		</div>

	</div>
	</a>

	<?php 
	} 
	?>
</div>
</div>