<p class="backLink">
	<a href="<?php echo $previous_route; ?>">< Previous Page</a>
</p>

<p><div style="float: left;">Displaying all projects that contain the tag &nbsp;</div> 
	<div class="tag" style="margin-right: 0; position: relative; bottom: 5px;"><?php echo $tag_name; ?></div>&nbsp;:	</p>

<div style="height: 10px;"></div>

<div class="row">
<div class="col-xs-10 col-xs-offset-1" id="portfolioDisplay">
	<?php 
	foreach($gallery_items as $item) {
	?>

	<a class="itemLink" href="/<?php echo $item->url_key; ?>">
	<?php
		// if portfolio item doesn't have an image (filename), just render
		// the blank image
		$empty_img = false;
		if ($item->img_filename === null) {
			$img_filename = 'placeholder.png';
			$empty_img = true;
		} else {
			$img_filename = $item->img_filename;
		}

		$img_filename = "/sym/images/" . $img_filename;
	?>
	<div class="itemThumbnail <?php if ($empty_img) { echo 'empty-img'; } ?>" style="background-image: url('<?php echo $img_filename; ?>');">
		
		<!-- 
			invisible until user hovers over the thumbnail.
			only background is filtered by opacity.
		-->
		<div class="thumbContent">
			<p class="thumbOverlay">
			</p>
			<p class="thumbText">
				<?php echo $item->title ?><br/>
				<span style="font-size: 14px; font-style: italic;"><?php echo $item->portfolio_type; ?></span>
			</p>
		</div>

	</div>
	</a>

	<?php
	}
	?>
</div>
</div>