<p class="backLink">
	<a href="/">Home</a> > <?php 
		if ($item->portfolio_type === "Personal Project") {
			echo '<a href="/personal">Personal Projects</a>';
		} else if ($item->portfolio_type === "Work History") {
			echo '<a href="/work">Work History</a>';
		}
	?> > <?php echo $item->title; ?>
</p>

<div class="itemDesc">
	<?php
		// if portfolio item doesn't have an image (filename), just render
		// the blank image
		$empty_img = false;
		if ($item->img_filename === null) {
			$img_filename = 'placeholder.png';
			$empty_img = true;
		} else {
			$img_filename = $item->img_filename;
		}

		$img_filename = "/sym/images/" . $img_filename;
	?>
	<?php if (!$empty_img): ?>
	<div class="crop">
		<a href="<?php echo $img_filename; ?>"><img src="<?php echo $img_filename; ?>"></a>
	</div>
	<?php endif; ?>

	<p class="portfolioItemTitle">
		<?php echo $item->title ?>

		<span style="font-size: 18px; font-style: italic; font-weight: 400; letter-spacing: 0;
			display: block; text-indent: 20px;">
			<?php echo $item->portfolio_type; ?>
		</span>
	</p>

	<p>
		<span style="letter-spacing: 1px;">Started:</span> <?php echo $item->start ?><br>
		<span style="letter-spacing: 1px;">Ended:</span> <?php echo $item->end ?><br>
		<span style="letter-spacing: 1px;">Last Updated:</span> <?php echo $item->updated ?><br>
		<span style="letter-spacing: 1px;">Link:</span> <?php 
			$project_link = $item->link;
			/*if (filter_var($project_link, FILTER_VALIDATE_URL) !== false) {
				echo '<a href="' . $project_link . '" target="_blank">' . $project_link . '</a>';
			} else {*/
				echo $project_link;
			//}
		?><br>
		<span style="letter-spacing: 1px;">Source:</span> <?php 
			$source_link = $item->source;
			/*if (filter_var($source_link, FILTER_VALIDATE_URL) !== false) {
				echo '<a href="' . $source_link . '" target="_blank">' . $source_link . '</a>';
			} else {*/
				echo $source_link;
			//}
		?>
	</p>

	<p style="margin-top: 35px;"><?php echo $item->description ?></p>
</div>

<div class="tags">
	<span style="
		display: block; float: left; margin-right: 20px; font-family: 'Raleway', serif; font-size: 20px; font-weight: 900; letter-spacing: 2px;">
		Tags:
	</span>
	<?php
		foreach($tags as $tag) {
	?>
		<a href="/tag/<?php echo $tag->id; ?>">
		<!--<?php /* <a style="cursor: pointer;"
			class="tagLink" data-tagid="<?php echo $tag->id; ?>" data-tagname="<?php echo $tag->name; ?>"> */ ?>-->
			<div class="tag"><?php echo $tag->name; ?></div>
		</a>
	<?php
		}
	?>

	<div style="height: 20px; clear: left;">&nbsp;</div>
</div>

<!--<script>
	$(document).ready(function() {
		$(".tagLink").click(function() {
			console.log("clicked");

			var id = $(this).data('tagid');
			var name = $(this).data('tagname');

			$.post("/tag", {'id': id, 'name': name, 'currentPage': '<?php //echo $_SERVER["REQUEST_URI"];?>'}, function(data, status) {
				console.log("success! Data: " + data);
			});
		});
	});
</script>-->