<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <link href='http://fonts.googleapis.com/css?family=Raleway' rel='stylesheet' type='text/css'>

        <meta charset="utf-8">
        <?php echo $this->headTitle("")?>

        <?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
                        ->prependStylesheet($this->basePath('css/style.css'))
                        ->prependStylesheet($this->basePath('css/bootstrap-theme.min.css'))
                        ->prependStylesheet($this->basePath('css/bootstrap.min.css'))
                        ->prependStylesheet($this->basePath('font-awesome/css/font-awesome.min.css')) ?>

        <!-- Scripts -->
        <?php echo $this->headScript()
            ->prependFile($this->basePath('js/bootstrap.min.js'))
            ->prependFile($this->basePath('js/jquery.min.js'))
            ->prependFile($this->basePath('js/respond.min.js'), 'text/javascript', array('conditional' => 'lt IE 9',))
            ->prependFile($this->basePath('js/html5shiv.js'),   'text/javascript', array('conditional' => 'lt IE 9',))
        ; ?>
    </head>
    <body>
        <img src="/img/tree_background.png" id="treeBg" />
        <header>
            <div id="title">
                <span id="titleText"><a href="/">Matthew Chan</a></span>
                <span>
                    <a href="/">Web Developer / Software Engineer</a>
                </span>
            </div>

            <!-- navigation bar -->
            <div id="nav">
                <ul>
                    <a href="/"><li>Home</li></a>
                    <a href="/personal"><li>Personal</li></a>
                    <a href="/work"><li>Work</li></a>
                    <a href="/sym/mattchan_html_resume.pdf"><li>My Resume</li></a>
                    <a href="https://github.com/MChan127" target="_blank"><li>My GitHub</li></a>
                </ul>
            </div>

            <span id="burgerMenuBtn"><img src="img/burger_menu.png" /></span>
        </header>

        <div id="content">
            <?php echo $this->content; ?>
        </div>

        <?php echo $this->partial('portfolio/index/mobile_menu.phtml'); ?>

        <script>
            //http://stackoverflow.com/a/18397475
            document.documentElement.className += 
            (("ontouchstart" in document.documentElement) ? ' touch' : ' no-touch');
        </script>
    </body>
</html>
